### PR TITLE
Fixed occasional crash in udFile_Close.

### PR DESCRIPTION
**Pull request by asunawu**
Fixed an occasional crash while testing AB#1672.

### CODE REVIEW

**Comment by dpev** [comment]
You beat me to the punch Sam. :) The change probably ought to be thread safe destruction, an interlocked compare exchange of the original pointer to atomically acquire ownership, and then complete destruction on success.

**Comment by samsinsane** [comment]
@dpev I just noticed that this crash occurs within `udFile_Load` and what I described really can't happen like that. This is a very strange crash.

**Comment by asunawu** [comment]
When it crashed, the pFile is a valid pointer, pFile->filenameCopyRequiresFree is true while pFile->pFilenameCopy is null pointer.

**Comment by dpev** [comment]
Looking at the callstack my guess is an overwrite corrupting the heap. If there's a bug with a repro case perhaps assign to me and I can look in depth tomorrow.

**Comment by dpev** [comment]
> When it crashed, the pFile is a valid pointer, pFile->filenameCopyRequiresFree is true while pFile->pFilenameCopy is null pointer.

udFree is a macro that tests the pointer for null before attempting to free, I'd be keen to step through the assembly and find out what's happening on this one

**Comment by asunawu** [comment]
It is one of the two crashes occurred during testing 1672.  In step 5, to create a new scene when the file is in pending(yellow triangle) state.

**Comment by samsinsane** [comment]
@asunawu Can you confirm the `fpLoad` pointer of `pFile`? It should be pointing to `udFile_GenericLoad` or `vcWebFile_Load` - I fear that my implementation of `vcWebFile_Load` might be causing this problem, so if it points to that then that would be a good place to start being critical of what happens.

**Comment by asunawu** [comment]
repo step:
1) I dragged "Models\Unsorted\Singapore Land Authority\obj\textured\output.obj" into a new scene.
2) Created another new scene while this file was in pending state.

**Comment by asunawu** [comment]
I think it might not be related to vcWebFile_Load? Is it a web file if I load from our share folder?

**Comment by samsinsane** [comment]
The callstack shows the tile renderer is requesting a file load this is the function that calls `udFile_Load`: https://github.com/Euclideon/vaultclient/blob/a79a1c8debca4332ce530d12d355066cd858e68b/src/rendering/vcTileRenderer.cpp#L197-L238

It could hit either a local file (`udFile_GenericLoad`) or a remote file (`vcWebFile_Load`), so it's possible that it's a problem in `vcWebFile_Load`.

**Comment by dpev** [comment]
Any chance vcWebFile_Load allocates an expected amount and reads the amount the web service gives it and potentially overshoots?

**Comment by samsinsane** [comment]
It's painfully basic (it's less code than the generic load function): https://github.com/Euclideon/vaultclient/blob/a79a1c8debca4332ce530d12d355066cd858e68b/src/vcWebFile.cpp#L10-L34 I don't think it overruns, but there's a couple of layers before hitting cURL at the end, so there's a chance we goofed something - though it's strange it only crashes during the scene change, so I'm probably steering this in the wrong direction.

**Comment by samsinsane** [comment]
I think I found what is causing this. `vcTileRenderer_ClearTiles` acquires a mutex lock, this is correct. However, it calls `Reset` on the `quadtree`, the nodes from the `quadtree` are used to populate `tileLoadList` which is what the mutex lock is actually for, not the `quadtree` member. You can see this here: https://github.com/Euclideon/vaultclient/blob/a79a1c8debca4332ce530d12d355066cd858e68b/src/rendering/vcTileRenderer.cpp#L304-L308 it unlocks the mutex and then continues to use a pointer into `quadtree` (if you search `tileLoadList.PushBack` you'll find two functions, both functions take a `vcQuadTreeNode*` which inevitably comes from the `quadtree`). You'll also note that despite removing the `pBestNode` from the `tileLoadList` it doesn't free the pointer or destroy the object at all - because it's owned by `quadtree` and there's no lock for that object.

After the mutex is unlocked, at any point this could be called on the node: https://github.com/Euclideon/vaultclient/blob/a79a1c8debca4332ce530d12d355066cd858e68b/src/vcQuadTree.cpp#L110-L124

@peterAdams1014 You're probably going to need to bring your expertise of `vcTileRenderer` and `vcQuadTree` and help Asuna come up with a solution. I would imagine a semaphore or mutex lock in the node itself would suffice that blocks the `vcQuadTree_CleanupNode` function until the `vcTileRenderer` has finished using the tile - though you may have a solution in mind that can bypass this synchronisation :thumbsup:

I think we can close this as the issue is likely due to a concurrency problem in the `vcTileRenderer` system that just happens to manifest here.

**Comment by asunawu** [comment]
Should create a new bug for it. 1672 is mainly about the loading delay.

**Pull request closed without merging**
